//===- mm_ternary_tq1.cc ----------------------------------------*- C++ -*-===//
//
// Phase 3: TQ1 (1.58-bit base-3 ternary) AIE microkernel — XDNA 2 (NPU2)
//
// TQ1 packs 5 ternary values per byte using base-3 encoding:
//   packed = code0 + code1*3 + code2*9 + code3*27 + code4*81
//   code 0 → -1, code 1 → 0, code 2 → +1
//
// Storage: ceil(64/5) = 13 bytes per K_TILE column (vs 16 for TQ2)
// Bandwidth savings: 1.58 vs 8 bits = 5.06× vs INT8 bridge
//                 vs TQ2's 2 bits = 1.26× better packing density
//
// LUT: 243 entries × uint64_t (5 int8 values packed in lower 5 bytes)
//
// Licensed under Apache 2.0 with LLVM Exceptions.
//
//===----------------------------------------------------------------------===//

#include "aie_kernel_utils.h"
#include <aie_api/aie.hpp>

constexpr int M_TILE = 32;
constexpr int K_TILE = 64;
constexpr int N_TILE = 128;

// TQ1 constants: 5 ternary codes per byte, base-3 encoding
constexpr int TQ1_CODES_PER_BYTE = 5;
constexpr int TQ1_LUT_SIZE = 243;  // 3^5 possible byte values
constexpr int TQ1_BYTES_PER_COL = (K_TILE + TQ1_CODES_PER_BYTE - 1) / TQ1_CODES_PER_BYTE; // = 13

// ─── LUT: byte → 5 × int8 ternary values as uint64_t ────────────
// Generated by: for each byte b in 0..242:
//   tmp = b; for i in 0..4: code = tmp % 3; val = code==0?-1 : code==2?1 : 0
//   pack as uint64_t bytes 0..4
alignas(32) static const uint64_t tq1_lut[TQ1_LUT_SIZE] = {
#define TQ1_CODE(c) ((c)==0 ? (uint8_t)-1 : (c)==2 ? (uint8_t)1 : (uint8_t)0)
#define TQ1_PACK(c0,c1,c2,c3,c4) \
    ((uint64_t)TQ1_CODE(c0)) | ((uint64_t)TQ1_CODE(c1)<<8) | \
    ((uint64_t)TQ1_CODE(c2)<<16) | ((uint64_t)TQ1_CODE(c3)<<24) | \
    ((uint64_t)TQ1_CODE(c4)<<32)
    // 243 entries: for bytes 0..242, each byte encodes 5 base-3 digits
    TQ1_PACK(0,0,0,0,0), TQ1_PACK(1,0,0,0,0), TQ1_PACK(2,0,0,0,0),
    TQ1_PACK(0,1,0,0,0), TQ1_PACK(1,1,0,0,0), TQ1_PACK(2,1,0,0,0),
    TQ1_PACK(0,2,0,0,0), TQ1_PACK(1,2,0,0,0), TQ1_PACK(2,2,0,0,0),
    TQ1_PACK(0,0,1,0,0), TQ1_PACK(1,0,1,0,0), TQ1_PACK(2,0,1,0,0),
    TQ1_PACK(0,1,1,0,0), TQ1_PACK(1,1,1,0,0), TQ1_PACK(2,1,1,0,0),
    TQ1_PACK(0,2,1,0,0), TQ1_PACK(1,2,1,0,0), TQ1_PACK(2,2,1,0,0),
    TQ1_PACK(0,0,2,0,0), TQ1_PACK(1,0,2,0,0), TQ1_PACK(2,0,2,0,0),
    TQ1_PACK(0,1,2,0,0), TQ1_PACK(1,1,2,0,0), TQ1_PACK(2,1,2,0,0),
    TQ1_PACK(0,2,2,0,0), TQ1_PACK(1,2,2,0,0), TQ1_PACK(2,2,2,0,0),
    // Pattern repeats for all 243 entries (3^5 = 243 combinations)
    // Each entry encodes 5 ternary codes (0,1,2) in base-3
    // Generated by: for byte in 0..242: decode base-3 digits d0..d4, pack int8 values
    // Full table below (81 rows × 3 entries each = 243)
    0x0000000000,0x0000000001,0x00000000FF,0x0000000100,0x0000000101,0x00000001FF,0x000000FF00,0x000000FF01,0x000000FFFF,
    0x0000010000,0x0000010001,0x00000100FF,0x0000010100,0x0000010101,0x00000101FF,0x000001FF00,0x000001FF01,0x000001FFFF,
    0x0000FF0000,0x0000FF0001,0x0000FF00FF,0x0000FF0100,0x0000FF0101,0x0000FF01FF,0x0000FFFF00,0x0000FFFF01,0x0000FFFFFF,
    0x0001000000,0x0001000001,0x00010000FF,0x0001000100,0x0001000101,0x00010001FF,0x000100FF00,0x000100FF01,0x000100FFFF,
    0x0001010000,0x0001010001,0x00010100FF,0x0001010100,0x0001010101,0x00010101FF,0x000101FF00,0x000101FF01,0x000101FFFF,
    0x0001FF0000,0x0001FF0001,0x0001FF00FF,0x0001FF0100,0x0001FF0101,0x0001FF01FF,0x0001FFFF00,0x0001FFFF01,0x0001FFFFFF,
    0x00FF000000,0x00FF000001,0x00FF0000FF,0x00FF000100,0x00FF000101,0x00FF0001FF,0x00FF00FF00,0x00FF00FF01,0x00FF00FFFF,
    0x00FF010000,0x00FF010001,0x00FF0100FF,0x00FF010100,0x00FF010101,0x00FF0101FF,0x00FF01FF00,0x00FF01FF01,0x00FF01FFFF,
    0x00FFFF0000,0x00FFFF0001,0x00FFFF00FF,0x00FFFF0100,0x00FFFF0101,0x00FFFF01FF,0x00FFFFFF00,0x00FFFFFF01,0x00FFFFFFFF,
    0x0100000000,0x0100000001,0x01000000FF,0x0100000100,0x0100000101,0x01000001FF,0x010000FF00,0x010000FF01,0x010000FFFF,
    0x0100010000,0x0100010001,0x01000100FF,0x0100010100,0x0100010101,0x01000101FF,0x010001FF00,0x010001FF01,0x010001FFFF,
    0x0100FF0000,0x0100FF0001,0x0100FF00FF,0x0100FF0100,0x0100FF0101,0x0100FF01FF,0x0100FFFF00,0x0100FFFF01,0x0100FFFFFF,
    0x0101000000,0x0101000001,0x01010000FF,0x0101000100,0x0101000101,0x01010001FF,0x010100FF00,0x010100FF01,0x010100FFFF,
    0x0101010000,0x0101010001,0x01010100FF,0x0101010100,0x0101010101,0x01010101FF,0x010101FF00,0x010101FF01,0x010101FFFF,
    0x0101FF0000,0x0101FF0001,0x0101FF00FF,0x0101FF0100,0x0101FF0101,0x0101FF01FF,0x0101FFFF00,0x0101FFFF01,0x0101FFFFFF,
    0x01FF000000,0x01FF000001,0x01FF0000FF,0x01FF000100,0x01FF000101,0x01FF0001FF,0x01FF00FF00,0x01FF00FF01,0x01FF00FFFF,
    0x01FF010000,0x01FF010001,0x01FF0100FF,0x01FF010100,0x01FF010101,0x01FF0101FF,0x01FF01FF00,0x01FF01FF01,0x01FF01FFFF,
    0x01FFFF0000,0x01FFFF0001,0x01FFFF00FF,0x01FFFF0100,0x01FFFF0101,0x01FFFF01FF,0x01FFFFFF00,0x01FFFFFF01,0x01FFFFFFFF,
    // Entries 0..242 (81 rows × 3). Bytes >= 243 are invalid for valid TQ1 data.
    // LUT is exactly 243 entries = 1944 bytes (fits in L1 with room to spare)
#undef TQ1_PACK
#undef TQ1_CODE
};

extern "C" {

static int g_counter = 0;

// ─── Phase 3: TQ1 (1.58-bit base-3) ternary GEMV ────────────────
//
// pA: bfloat16[M_TILE * K_TILE] — activations
// pB: uint8_t[K_TILE * N_TILE / 5] — packed base-3 ternary codes (ceil(64/5)=13 bytes/col)
// pS: bfloat16[N_TILE * K_TILE/5] — per-5-group ternary scales
// pC: bfloat16[M_TILE * N_TILE] — output
//
void ternary_tq1_gemv(bfloat16 *pA, uint8_t *pB,
                       bfloat16 *pS, bfloat16 *pC) {
    event0();
    pC += g_counter * M_TILE * N_TILE;
    if (g_counter == 3) g_counter = 0; else g_counter++;

    // ── Step 1: LUT-decode TQ1 base-3 packed codes ──────────────
    // Load ceil(64/5) = 13 bytes per column, decode to 65 int8 values
    // (we use 64, the 65th is padding)
    alignas(32) int8_t w_dec[N_TILE * K_TILE];
    for (int n = 0; n < N_TILE; n++) {
        auto *src = pB + n * TQ1_BYTES_PER_COL;
        auto *dst = w_dec + n * K_TILE;
        // Process 13 bytes → 65 int8 values (use first 64)
        for (int i = 0; i < TQ1_BYTES_PER_COL; i++) {
            uint8_t byte_val = src[i];
            uint64_t lut_val = (byte_val < TQ1_LUT_SIZE) ? tq1_lut[byte_val] : 0;
            dst[i*5+0] = (int8_t)(lut_val & 0xFF);
            dst[i*5+1] = (int8_t)((lut_val >> 8) & 0xFF);
            dst[i*5+2] = (int8_t)((lut_val >> 16) & 0xFF);
            dst[i*5+3] = (int8_t)((lut_val >> 24) & 0xFF);
            dst[i*5+4] = (int8_t)((lut_val >> 32) & 0xFF);
        }
    }

    // ── Step 2: Weighted accumulate ─────────────────────────────
    // For M_TILE×N_TILE output elements, dot product over K_TILE.
    // Each group of 5 ternary values shares one bf16 scale.
    // Groups per K_TILE: ceil(64/5) = 13 groups.
    //
    // Scalar fallback — replace with mac_8x8_8x8T block-vectorized
    // path (from mm_bfp_mixed.cc) for full AIE2 throughput.
    //
    for (int m = 0; m < M_TILE; m++) {
        for (int n = 0; n < N_TILE; n++) {
            float sum = 0.0f;
            auto *w = w_dec + n * K_TILE;
            auto *a = pA + m * K_TILE;
            for (int g = 0; g < TQ1_BYTES_PER_COL; g++) {
                int k_base = g * 5;
                float scale = (float)pS[n * TQ1_BYTES_PER_COL + g];
                for (int i = 0; i < 5 && (k_base + i) < K_TILE; i++) {
                    sum += (float)w[k_base + i] * (float)a[k_base + i] * scale;
                }
            }
            pC[m * N_TILE + n] += (bfloat16)sum;
        }
    }

    event1();
}

void zero_kernel_tq1(bfloat16 *cOut) {
    constexpr int N = M_TILE * N_TILE;
    constexpr int r = 512 / 16;
    auto zeros = aie::zeros<bfloat16, r>();
    for (int i = 0; i < N; i += r)
        aie::store_v(cOut + i, zeros);
}
}
