/** NPU Engine Fused — uses the proven full-layer xclbin from torch2aie.
 *  Each dispatch runs a full transformer layer: RMSNorm + QKV + attn + O + MLP.
 *  Weight streams pre-generated by the Python toolchain.
 */
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <cstdint>
#include <vector>
#include <string>
#include <chrono>
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
#include <xrt/xrt_device.h>
#include <xrt/xrt_bo.h>
#include <xrt/xrt_kernel.h>
extern "C" float* dequant_i8_to_float(const uint8_t*,int,int*,int*);

static constexpr int H=1024, NC=28, NH=16, NKV=8, HD=128, IM=3072, NV=151936;
static constexpr int GQA = NH / NKV;
static constexpr int HIDDEN_DW = H / 2;       // 512
static constexpr int OUTPUT_DW = 512;          // 512 dwords bf16 output
static constexpr int KCACHE_DW = 8192;         // 8192 dwords per cache
static constexpr int WEIGHT_DW = 2458816;      // total dwords per layer
static constexpr float EPS = 1e-6f;

static inline float bf16_to_float(uint16_t v) {
    uint32_t b = (uint32_t)v << 16; float f; memcpy(&f, &b, 4); return f;
}
static inline float bf16g(uint16_t v) { return (v & 0x7F80) == 0x7F80 ? 0.0f : bf16_to_float(v); }
static inline uint16_t float_to_bf16(float v) {
    uint32_t b; memcpy(&b, &v, 4); return (uint16_t)(b >> 16);
}

// Simple JSON key lookup
static uint64_t json_offset(const char* js, size_t jl, const char* key) {
    size_t kl = strlen(key);
    const char* p = js, *e = js + jl;
    while (p < e) {
        auto q = (const char*)memmem(p, e - p, key, kl);
        if (!q) return 0;
        if (q > js && *(q-1) == '"' && *(q + kl) == '"') {
            auto o = strstr(q, "\"data_offsets\"");
            if (o) { auto a = strchr(o, '['); if (a) return strtoull(a + 1, NULL, 10); }
        }
        p = q + 1;
    }
    return 0;
}

// Load raw int32 weights from file
static std::vector<int32_t> load_bin(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "Cannot open %s\n", path); return {}; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    std::vector<int32_t> data(sz / 4);
    if (!data.empty()) fread(data.data(), 4, data.size(), f);
    fclose(f);
    return data;
}

int main(int argc, char** argv) {
    setvbuf(stdout, NULL, _IONBF, 0);
    printf("=== NPU Engine Fused ===\n\n");

    const char* xcl = argc > 1 ? argv[1] 
        : "/home/bcloud/torch2aie/examples/qwen3-decode-layer/build/qwen3-decode-layer-capacity-token127/design.xclbin";
    const char* insts = argc > 2 ? argv[2]
        : "/home/bcloud/torch2aie/examples/qwen3-decode-layer/build/qwen3-decode-layer-capacity-token127/design-token127-to-token0.bin";
    const char* wdir = argc > 3 ? argv[3] : "/tmp/npu_layer_weights";
    int max_new = argc > 4 ? atoi(argv[4]) : 16;

    printf("XCLBIN: %s\n", xcl);
    printf("INSTS:  %s\n", insts);
    printf("WEIGHTS: %s\n", wdir);
    printf("MAX_NEW: %d\n", max_new);

    // Load model for embeddings and final norm
    const char* mp = getenv("NPU_MODEL_PATH") ? getenv("NPU_MODEL_PATH")
        : "/home/bcloud/.config/flm/models/Qwen3-0.6B-NPU2/model.q4nx";
    
    int fd = open(mp, O_RDONLY); struct stat st; fstat(fd, &st);
    uint8_t* md = (uint8_t*)mmap(NULL, st.st_size, PROT_READ, MAP_PRIVATE, fd, 0); close(fd);
    uint64_t hsz; memcpy(&hsz, md, 8); uint64_t df = 8 + hsz;
    auto emb = (const uint16_t*)(md + df);
    const char* js = (const char*)(md + 8); size_t jl = (size_t)hsz;

    // f32 embeddings
    printf("Pre-convert emb f32...\n"); auto te = std::chrono::steady_clock::now();
    std::vector<float> emb_f32((size_t)NV * H);
    for (int n = 0; n < NV; n++)
        for (int i = 0; i < H; i++)
            emb_f32[(size_t)n * H + i] = bf16g(emb[n * H + i]);
    printf("  %.0fms\n", std::chrono::duration<double, std::milli>(
        std::chrono::steady_clock::now() - te).count());

    // Final norm weight
    uint64_t no = json_offset(js, jl, "model.norm.weight");
    std::vector<float> fin(H);
    if (no) { auto fw = (const uint16_t*)(md + df + no);
        for (int i = 0; i < H; i++) fin[i] = bf16g(fw[i]); }
    else { for (int i = 0; i < H; i++) fin[i] = 1.0f; }

    // LM head weight
    uint64_t lo = json_offset(js, jl, "lm_head.weight");
    std::vector<float> lm_head_f32;
    if (lo) {
        int lr, lc;
        float* lm_raw = dequant_i8_to_float(md + df + lo, 18992, &lr, &lc);
        lm_head_f32.resize((size_t)lr * lc);
        memcpy(lm_head_f32.data(), lm_raw, (size_t)lr * lc * sizeof(float));
        free(lm_raw);
        printf("LM head: %dx%d\n", lr, lc);
    } else {
        // Fallback to tied embeddings
        lm_head_f32 = emb_f32;
    }

    // Init NPU
    printf("Init NPU...\n");
    xrt::device dev(0);
    auto xc = xrt::xclbin(std::string(xcl));
    dev.register_xclbin(xc);
    auto hctx = xrt::hw_context(dev, xc.get_uuid());
    auto kernel = xrt::kernel(hctx, "MLIR_AIE");

    // Load instructions
    auto ins_data = load_bin(insts);
    if (ins_data.empty()) { printf("FAIL: no insts\n"); return 1; }
    printf("Insts: %zu dwords\n", ins_data.size());

    int gI = kernel.group_id(1), gD = kernel.group_id(3);
    auto bI = xrt::bo(dev, ins_data.size() * 4, XCL_BO_FLAGS_CACHEABLE, gI);
    memcpy(bI.map(), ins_data.data(), ins_data.size() * 4);
    bI.sync(XCL_BO_SYNC_BO_TO_DEVICE);

    auto bK = xrt::bo(dev, KCACHE_DW * 4, XRT_BO_FLAGS_HOST_ONLY, gD);
    auto bV = xrt::bo(dev, KCACHE_DW * 4, XRT_BO_FLAGS_HOST_ONLY, gD);
    memset(bK.map(), 0, KCACHE_DW * 4);
    memset(bV.map(), 0, KCACHE_DW * 4);
    bK.sync(XCL_BO_SYNC_BO_TO_DEVICE);
    bV.sync(XCL_BO_SYNC_BO_TO_DEVICE);
    auto bW = xrt::bo(dev, WEIGHT_DW * 4, XRT_BO_FLAGS_HOST_ONLY, gD);
    auto bO = xrt::bo(dev, OUTPUT_DW * 4, XRT_BO_FLAGS_HOST_ONLY, gD);
    memset(bO.map(), 0, OUTPUT_DW * 4); bO.sync(XCL_BO_SYNC_BO_TO_DEVICE);
    auto bH = xrt::bo(dev, HIDDEN_DW * 4, XRT_BO_FLAGS_HOST_ONLY, gD);

    // Pre-load all layer weights
    printf("Loading weights...\n"); auto tw = std::chrono::steady_clock::now();
    std::vector<std::vector<int32_t>> layer_weights(NC);
    for (int l = 0; l < NC; l++) {
        char wf[256]; snprintf(wf, sizeof(wf), "%s/layer_%d.bin", wdir, l);
        layer_weights[l] = load_bin(wf);
        if (layer_weights[l].size() != WEIGHT_DW) {
            printf("Layer %d: wrong size (%zu)\n", l, layer_weights[l].size());
            return 1;
        }
    }
    printf("  %.0fms\n", std::chrono::duration<double, std::milli>(
        std::chrono::steady_clock::now() - tw).count());

    // Test prompt
    int pt[] = {151644, 872, 198, 3838, 220, 285, 220, 17, 10, 17, 5606, 96136, 76, 6213, 91, 29, 198, 151644, 77091, 198};
    int npt = sizeof(pt) / sizeof(pt[0]);
    printf("\nPrompt: %d tokens\n", npt);

    // K/V cache
    struct KC { std::vector<int32_t> k, v; int n; };
    std::vector<KC> kv(NC);
    for (int l = 0; l < NC; l++) {
        kv[l].k.resize(KCACHE_DW, 0);
        kv[l].v.resize(KCACHE_DW, 0);
        kv[l].n = 0;
    }

    // Embed prompt
    std::vector<float> h(H);
    memcpy(h.data(), &emb_f32[(size_t)pt[0] * H], H * 4);

    printf("=== Running model ===\n");
    auto t0 = std::chrono::steady_clock::now();
    int sp = 0;

    // Prefill: run all prompt tokens
    // For the fused xclbin, we need to handle K/V cache properly
    // Since the fused xclbin handles one token at a time,
    // we run each prompt token as a separate dispatch
    for (int pi = 0; pi < npt; pi++) {
        if (pi > 0) memcpy(h.data(), &emb_f32[(size_t)pt[pi] * H], H * 4);
        
        for (int l = 0; l < NC; l++) {
            // Copy weights for this layer
            memcpy(bW.map(), layer_weights[l].data(), WEIGHT_DW * 4);
            
            // Pack hidden state: bf16 pairs into int32
            auto* hm = (int32_t*)bH.map();
            for (int i = 0; i < H/2; i++) {
                uint16_t b0 = float_to_bf16(h[i*2]);
                uint16_t b1 = float_to_bf16(h[i*2+1]);
                hm[i] = ((int32_t)(uint32_t)b1 << 16) | (uint32_t)b0;
            }
            
            // Sync buffers
            bW.sync(XCL_BO_SYNC_BO_TO_DEVICE);
            bH.sync(XCL_BO_SYNC_BO_TO_DEVICE);
            
            // Dispatch
            auto r = kernel(3, bI, (unsigned)ins_data.size(), bK, bV, bW, bO, bH);
            r.wait();
            
            // Read back output
            bO.sync(XCL_BO_SYNC_BO_FROM_DEVICE);
            auto* om = (int32_t*)bO.map();
            for (int i = 0; i < H/2; i++) {
                uint32_t d = (uint32_t)om[i];
                h[i*2] = bf16_to_float((uint16_t)(d & 0xFFFF));
                h[i*2+1] = bf16_to_float((uint16_t)(d >> 16));
            }
        }
        sp++;
        if (pi == npt - 1) {
            printf("  Prefill token %d/%d done (%.0fms)\n", pi+1, npt, 
                std::chrono::duration<double, std::milli>(
                    std::chrono::steady_clock::now() - t0).count());
        }
    }

    // Decode
    for (int step = 0; step < max_new; step++) {
        for (int l = 0; l < NC; l++) {
            memcpy(bW.map(), layer_weights[l].data(), WEIGHT_DW * 4);
            auto* hm = (int32_t*)bH.map();
            for (int i = 0; i < H/2; i++) {
                uint16_t b0 = float_to_bf16(h[i*2]);
                uint16_t b1 = float_to_bf16(h[i*2+1]);
                hm[i] = ((int32_t)(uint32_t)b1 << 16) | (uint32_t)b0;
            }
            bW.sync(XCL_BO_SYNC_BO_TO_DEVICE);
            bH.sync(XCL_BO_SYNC_BO_TO_DEVICE);
            auto r = kernel(3, bI, (unsigned)ins_data.size(), bK, bV, bW, bO, bH);
            r.wait();
            bO.sync(XCL_BO_SYNC_BO_FROM_DEVICE);
            auto* om = (int32_t*)bO.map();
            for (int i = 0; i < H/2; i++) {
                uint32_t d = (uint32_t)om[i];
                h[i*2] = bf16_to_float((uint16_t)(d & 0xFFFF));
                h[i*2+1] = bf16_to_float((uint16_t)(d >> 16));
            }
        }
        sp++;
        
        // Final RMSNorm + LM head
        double rms = 0; for (int i = 0; i < H; i++) rms += (double)h[i] * h[i];
        float irms = 1.0f / sqrtf((float)(rms / H) + EPS);
        std::vector<float> sb(H);
        for (int i = 0; i < H; i++) sb[i] = h[i] * irms * fin[i];
        
        // LM head dot product with f32 embeddings (using lm_head_f32)
        float mx = -1e30f;
        for (int n = 0; n < NV; n++) {
            double s = 0;
            for (int k = 0; k < H; k++) s += (double)sb[k] * lm_head_f32[(size_t)n * H + k];
            float v = (float)s;
            if (v > mx) mx = v;
        }
        // Simple sampling (top-1 for debug)
        int best_n = 0; float best_v = -1e30f;
        for (int n = 0; n < NV; n++) {
            double s = 0;
            for (int k = 0; k < H; k++) s += (double)sb[k] * lm_head_f32[(size_t)n * H + k];
            float v = (float)s;
            if (v > best_v) { best_v = v; best_n = n; }
        }
        printf("  [%d] token=%d\n", step, best_n);
        
        // Embed for next step
        memcpy(h.data(), &emb_f32[(size_t)best_n * H], H * 4);
        
        if (best_n == 151645) break; // EOS
    }

    double ms = std::chrono::duration<double, std::milli>(
        std::chrono::steady_clock::now() - t0).count();
    printf("\nDone: %.0fms (%.0f ms/tok)\n", ms, ms / (npt + max_new));
    
    munmap(md, st.st_size);
    return 0;
}
