#!/usr/bin/env bash
# ── 1bit.systems numbers — single source of truth ──
# Auto-generated by scripts/measure-binary.sh on build.
# Do not edit manually — run `npm run build` or `npm run measure` to update.
set -euo pipefail
cd "$(dirname "$0")/.."

# Measure binaries
measure() { [ -f "$1" ] && echo $(( ($(stat -c%s "$1") + 512) / 1024 )) || echo "0"; }

FUSED=$(measure engine/npu/build/npu_engine_fused)
SPEC=$(measure spec-decode/build/npu_spec_decode)
MAIN=$(measure engine/npu/build/npu_engine)
UNIVERSAL=$(measure engine/npu/build/npu_engine_universal)
SERVER=$(measure engine/npu/build/npu_engine_server)

# ── Write numbers.json ──
cat > site/numbers.json <<EOF
{
  "binary": {
    "fused_kb": ${FUSED},
    "spec_decode_kb": ${SPEC},
    "main_engine_kb": ${MAIN},
    "universal_kb": ${UNIVERSAL},
    "server_kb": ${SERVER}
  },
  "benchmarks": {
    "npu_validated_tok_s": 94,
    "npu_fused_raw_tok_s": 291,
    "gpu_ternary_tok_s": 279,
    "gpu_1bit_llama_tok_s": 381,
    "gpu_f16_baseline_tok_s": 22,
    "tflops": 55.7
  },
  "models": 73,
  "backends": 6
}
EOF

# ── Update site/index.html ──
sed -i \
  -e "s/[0-9]\+ KB Single Binary/${SPEC} KB Single Binary/g" \
  -e "s/[0-9]\+ KB single binary/${SPEC} KB single binary/g" \
  -e "s/\"[0-9]\+ KB single binary\"/\"${SPEC} KB single binary\"/g" \
  -e "s/[0-9]\+ KB Single/${SPEC} KB Single/g" \
  -e "s/>[0-9]\+ KB binary</>${SPEC} KB binary</g" \
  -e "s/>[0-9]\+ KB unified/>${SPEC} KB unified/g" \
  -e "s/>[0-9]\+ KB · MIT</>${SPEC} KB · MIT</g" \
  -e "s/[0-9]\+ KB fused layer/${FUSED} KB fused layer/g" \
  -e "s/\"[0-9]\+ KB fused layer\"/\"${FUSED} KB fused layer\"/g" \
  -e "s/<span class=\"val\">[0-9]\+ <span>KB<\\/span>/<span class=\"val\">${SPEC} <span>KB<\\/span>/g" \
  -e "s/fused layer · one xclbin/spec-decode · NPU+GPU+CPU/g" \
  site/index.html

# ── Update site/demo/index.html ──
sed -i \
  -e "s/[0-9]\+ KB/${SPEC} KB/g" \
  site/demo/index.html 2>/dev/null || true

# ── Update site/demo/gpu.html ──
sed -i \
  -e "s/[0-9]\+ KB/${FUSED} KB/g" \
  site/demo/gpu.html 2>/dev/null || true

echo ""
echo "  fused:    ${FUSED} KB"
echo "  spec:     ${SPEC} KB  ← main binary"
echo "  main:     ${MAIN} KB"
echo "  universal: ${UNIVERSAL} KB"
echo "  server:   ${SERVER} KB"
echo "  → site/index.html updated"
echo "  → site/numbers.json written"
