# CMake generated Testfile for 
# Source directory: /home/bcloud/1bit-systems
# Build directory: /home/bcloud/1bit-systems/build_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_medusa_skeleton]=] "/home/bcloud/1bit-systems/build_test/test_medusa_skeleton")
set_tests_properties([=[test_medusa_skeleton]=] PROPERTIES  LABELS "host" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;604;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_gguf_reader_dequant]=] "/home/bcloud/1bit-systems/build_test/test_gguf_reader_dequant")
set_tests_properties([=[test_gguf_reader_dequant]=] PROPERTIES  LABELS "host" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;614;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_backend]=] "/home/bcloud/1bit-systems/build_test/test_backend")
set_tests_properties([=[test_backend]=] PROPERTIES  LABELS "host" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;617;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_standalone_nock]=] "/home/bcloud/1bit-systems/build_test/test_standalone_nock")
set_tests_properties([=[test_standalone_nock]=] PROPERTIES  LABELS "gpu_required" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;623;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_prim_and_attn]=] "/home/bcloud/1bit-systems/build_test/test_prim_and_attn")
set_tests_properties([=[test_prim_and_attn]=] PROPERTIES  LABELS "gpu_required" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;625;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_ternary_gemm_smallm]=] "/home/bcloud/1bit-systems/build_test/test_ternary_gemm_smallm")
set_tests_properties([=[test_ternary_gemm_smallm]=] PROPERTIES  LABELS "gpu_required" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;627;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_sherry_gemv]=] "/home/bcloud/1bit-systems/build_test/test_sherry_gemv")
set_tests_properties([=[test_sherry_gemv]=] PROPERTIES  LABELS "gpu_required" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;629;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_bonsai_gemv]=] "/home/bcloud/1bit-systems/build_test/test_bonsai_gemv")
set_tests_properties([=[test_bonsai_gemv]=] PROPERTIES  LABELS "gpu_required" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;631;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_zaya_moe_gemv]=] "/home/bcloud/1bit-systems/build_test/test_zaya_moe_gemv")
set_tests_properties([=[test_zaya_moe_gemv]=] PROPERTIES  LABELS "gpu_required" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;633;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_block_scaled_ternary]=] "/home/bcloud/1bit-systems/build_test/test_block_scaled_ternary")
set_tests_properties([=[test_block_scaled_ternary]=] PROPERTIES  LABELS "gpu_required" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;635;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_cca_attn]=] "/home/bcloud/1bit-systems/build_test/test_cca_attn")
set_tests_properties([=[test_cca_attn]=] PROPERTIES  LABELS "gpu_required" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;637;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_wmma_i8_gemv]=] "/home/bcloud/1bit-systems/build_test/test_wmma_i8_gemv")
set_tests_properties([=[test_wmma_i8_gemv]=] PROPERTIES  LABELS "gpu_required" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;639;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_bonsai_e2e]=] "/home/bcloud/1bit-systems/build_test/test_bonsai_e2e")
set_tests_properties([=[test_bonsai_e2e]=] PROPERTIES  LABELS "gpu_required;model_required;e2e" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;642;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_sherry_e2e]=] "/home/bcloud/1bit-systems/build_test/test_sherry_e2e")
set_tests_properties([=[test_sherry_e2e]=] PROPERTIES  LABELS "gpu_required;model_required;e2e" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;644;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_generic_attention]=] "/home/bcloud/1bit-systems/build_test/test_generic_attention")
set_tests_properties([=[test_generic_attention]=] PROPERTIES  LABELS "model_required;e2e" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;661;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_pipeline_real]=] "/home/bcloud/1bit-systems/engine/fusion/zero_copy/test_pipeline_real")
set_tests_properties([=[test_pipeline_real]=] PROPERTIES  LABELS "gpu_required;npu_required" SKIP_RETURN_CODE "77" WORKING_DIRECTORY "/home/bcloud/1bit-systems" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;929;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
add_test([=[test_oscar_attn_decode]=] "/home/bcloud/1bit-systems/build_test/test_oscar_attn_decode")
set_tests_properties([=[test_oscar_attn_decode]=] PROPERTIES  LABELS "gpu_required" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/bcloud/1bit-systems/CMakeLists.txt;1033;add_test;/home/bcloud/1bit-systems/CMakeLists.txt;0;")
subdirs("_deps/cpp_httplib-build")
subdirs("_deps/nlohmann_json-build")
subdirs("_deps/ftxui-build")
subdirs("zinc_cpp_build")
